name: Docker Image CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "xpider/xpider"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: "IMAGE"
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
      
      - name: Deploy Docker image to self-hosted runner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SELF_HOSTED_RUNNER_HOST }}
          username: ${{ secrets.SELF_HOSTED_RUNNER_USERNAME }}
          password: ${{ secrets.SELF_HOSTED_RUNNER_PASSWORD }}
          port: ${{ secrets.SELF_HOSTED_RUNNER_SSH_PORT }}
          script: |
            docker pull IMAGE
            docker run -d --name my-container IMAGE
